### ISSUE TITLE
Ustawienia resetują się po załadowaniu wtyczki (po każdym włączeniu przeglądarki)

### ISSUE THREAD

**Issue by Marioneq4958** [banocean/ifv#19]
https://github.com/banocean/ifv/blob/main/apply.js#L92

![obraz](https://github.com/user-attachments/assets/29202ca2-843d-4efe-8d15-b820fc485d45)

**Comment by PanLiszka** [comment]
Someone mark this as bug

**Comment by banocean** [comment]
> https://github.com/banocean/ifv/blob/main/apply.js#L92
> 
> ![obraz](https://private-user-images.githubusercontent.com/91561391/363146206-29202ca2-843d-4efe-8d15-b820fc485d45.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUwNDM0MDAsIm5iZiI6MTcyNTA0MzEwMCwicGF0aCI6Ii85MTU2MTM5MS8zNjMxNDYyMDYtMjkyMDJjYTItODQzZC00ZWZlLThkMTUtYjgyMGZjNDg1ZDQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODMwVDE4MzgyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFjNjI4ZjM4ZDg2Mjc2MGRmNTc0Mjg5MDFiMjNmYjhkNjcwMTY1NThmOWQwYjA5ZTcwMmRkOWYxZmY3ZjUyZDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0pR2Wx-nDQpBwn4T68quYIhgG0KnxALVSbX8FjF6akw)

https://groups.google.com/a/chromium.org/g/chromium-extensions/c/O8fraUImqpE?pli=1

**Comment by PanLiszka** [comment]
no to trzeba dodać do manifestu tak?

**Comment by banocean** [comment]
> no to trzeba dodać do manifestu tak?

jak już zobaczyłeś (konwersacja na dc), to nie jest z tym problem, ale przekroczenie 1KB z tym obiektem wstawionym wydaje się możliwe i tak
