### ISSUE TITLE
Ukrywanie przedmiotów bez ocen

### ISSUE THREAD

**Issue by Marioneq4958** [banocean/ifv#45]

**Comment by banocean** [comment]
Nie wiem, czy chcemy to robić. Trzeba sprawdzić dokładnie, czy nie znika część informacji w ten sposób i może wybrać implementację czegoś, co będzie pozwalało pokazać te informacje/ukryte przedmioty

**Comment by banocean** [comment]
> Nie wiem, czy chcemy to robić. Trzeba sprawdzić dokładnie, czy nie znika część informacji w ten sposób i może wybrać implementację czegoś, co będzie pozwalało pokazać te informacje/ukryte przedmioty

Do tego cały deisgn ocen jest taki sobie, więc może by wypadało to zmienić
