### ISSUE TITLE
Przekierowanie do strony logowania na `dziennik-uczen.vulcan.net.pl` podobnie jak na `eduvulcan.pl`

### ISSUE THREAD

**Issue by rotkiW285** [banocean/ifv#54]
Fajnie by było jakby rozszerzenie, podobnie jak na stronie eduvulcan, przekierowywało od razu na stronę logowania pod adresem `https://dziennik-uczen.vulcan.net.pl/[symbol]/LoginEndpoint.aspx`

**Comment by KPniX** [comment]
Jest to prosta modyfikacja skryptu z przekierowywaniem do strony logowania eduVULCAN. Mam nawet gotowy skrypt i przesyłam najnowszą wersje wtyczki z tym dodatkiem. Działa na Edge, ale nie wiem, jak na innych i nie można z panelu tego dodatku wyłączyć (nie rozgryzłem jeszcze tego):
[ifv-kpnix.zip](https://github.com/user-attachments/files/16921359/ifv-kpnix.zip)

**Comment by PanLiszka** [comment]
> Jest to prosta modyfikacja skryptu z przekierowywaniem do strony logowania eduVULCAN. Mam nawet gotowy skrypt i przesyłam najnowszą wersje wtyczki z tym dodatkiem. Działa na Edge, ale nie wiem, jak na innych i nie można z panelu tego dodatku wyłączyć (nie rozgryzłem jeszcze tego):
> [ifv-kpnix.zip](https://github.com/user-attachments/files/16921359/ifv-kpnix.zip)
> 
> Edit: Jest to jednak trochę problematyczne, kiedy ktoś chce aktywować nowe konto, ale:
> 1. Na kartkach jest odnośnik bezpośredni: aktywuj.vulcan.edu.pl
> 2. Myślę, że nikt nie będzie instalował wtyczki przed aktywacją
> Alternatywnie można albo ukryć przycisk do logowania do eduVULCAN i ewentualnie wprowadzić autoprzekierowanie po pewnym czasie (i takową informacją).

Jak coś to stwórz pr'a

**Comment by rotkiW285** [comment]
> i nie można z panelu tego dodatku wyłączyć (nie rozgryzłem jeszcze tego)
ta opcja działa, ale strona się nie odświeża
