### ISSUE TITLE
Autouzupełnianie loginu w dziennik-logowanie.vulcan.net.pl po wprowadzeniu lokalnego i łatwiejszego do zapamiętania nicku (tak, jak w eduvulcan.pl, tylko lokalnie).

### ISSUE THREAD

**Issue by KPniX** [banocean/ifv#57]
Uważam, że jest to trudne, chodź nie niemożliwe (przecież adblocki gdzieś zapisują swoje bazy). Jednak usprawniłoby logowanie do konta zwykłego (zwłaszcza, jeśli jest konieczność posiadania większej liczby kont dla np. większej ilości dzieci).
Fajnie by było, jeśli wybieralibyśmy je z listy i można było wybrać między listą a ręcznym wpisywaniem.

**Comment by banocean** [comment]
We will use proposed solution in #43
