### ISSUE TITLE
Podświetlanie opcji "Więcej" w bottom barze, gdy odpalona podstrona się na nim nie znajduje

### ISSUE THREAD

**Issue by Blookusny** [banocean/ifv#78]
prosze was tylko o dodanie `else i = 4` do highlightsow i zaspokoi to wszelkie moje potrzeby 🙏
![3966](https://github.com/user-attachments/assets/25ceba00-44f1-4005-be87-baa858bb882e)

**Comment by banocean** [comment]
Jak dla mnie to zaznaczenie opcji więcej by wskazywało, że właśnie mamy ją, lub jakiś modal na tej stronie włączony. Po konsultacji tego z innymi stwierdziłem, że nie będzie to bardziej intuicyjne.

Możliwe, że później zaimplementujemy to tak by strony wyświetlały header taki jak mają modale ze strzałką do cofania, wtedy by to było bardziej intuicyjne.
